### ISSUE TITLE
Error Input Rank 

### ISSUE THREAD

**Issue by leohpj** [irimia-laboratory/USC_BA_estimator#1]
Dear Irimia lab, thank you very much for for making this code open access.
when running your code on our network i experienced this issue:
########################################
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: input Got: 4 Expected: 5 Please fix either the inputs or the model.
########################################
Is there a possible fix?
Again, thank you very much!

fixed by adding a new dimension "1" at and to the input "brains.npy"

**Comment by aamgalan** [comment]
Thanks leohpj! 
We fixed the 2 issues you encountered. 
1. The dimensionality issue was fixed by adding another dummy axis into the 3D image to give it a 4th dimension. This is what TF model specification seems to like. 
2. We noticed a bug in printing the predicted age. Despite adding the 22 (offset), we were printing the pre-addition age, causing confusion. It is now fixed so feel free to pull now. 
Thanks!
